#!/bin/bash

# Build docker image
git clone https://github.com/jlachowski/docker-graphite /tmp/docker-graphite
docker build -q=true -t jlachowski/graphite /tmp/docker-graphite
rm -rf /tmp/docker-graphite
